spring.application.name=starter_restapi

info.app.description=Template Backend Java Authentication JWT TOKEN By Frezneel
info.app.version=1.0.0
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Jakarta
# Server Port
server.port=8080

# Database Configuration (Postgres Template)
spring.datasource.url=jdbc:postgresql://localhost:5432/templateBackendJava
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.security.jwt.secretkey=P3EmzRs1CSPemhPv5tseb+3NWsuK0ONu98nyPbu2Ze7JO8/pIUlBdprkeletYbSdkbjrIvvShlY0JPiJ6dE47w==
app.security.jwt.expiration=86400000

# CORS Configurations
spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
